/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gold.account;

import DataBase.ConectionDataBase;
import static DataBase.ConectionDataBase.AutoId;
import static DataBase.ConectionDataBase.ExecuteAnyQuery;
import static DataBase.ConectionDataBase.newBalance;
import DataBase.Tools;
import com.sun.org.apache.xerces.internal.parsers.IntegratedParserConfiguration;
import java.io.InputStream;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.lang.ArrayUtils;

/**
 *
 * @author Masrawy
 */
public class Clearing extends javax.swing.JFrame {

    /**
     * Creates new form Clearing
     */
    
    double HworKer , f;
    private String id_work = "";
    String id_deal ="";
    public Clearing() {
        initComponents();
        txtHworker.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                double edWorker = Double.valueOf(txtHworker.getText());
                double difr =  HworKer - edWorker;
                double allDif = difr * Integer.parseInt(txtCount.getText());
                double toClear =  f + allDif;
                txtClear.setText(String.valueOf(toClear));
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                double edWorker = Double.valueOf(txtHworker.getText());
                double difr =  HworKer - edWorker;
                double allDif = difr * Integer.parseInt(txtCount.getText());
                double toClear =  f + allDif;
                txtClear.setText(String.valueOf(toClear));

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comWork = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtwight = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtExpention = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCount = new javax.swing.JLabel();
        tabPanel = new javax.swing.JTabbedPane();
        Ghorbal = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        txtLoder = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        txtTthirds = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        txtGhorbal = new javax.swing.JLabel();
        txt5 = new javax.swing.JLabel();
        txtCar = new javax.swing.JLabel();
        txtworks = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        txtoneWork = new javax.swing.JLabel();
        txt6 = new javax.swing.JLabel();
        Ston = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtHfilter = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHtow = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txxtHassets = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        machin = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        comAccount = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        txtHworker = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtClear = new javax.swing.JLabel();
        edWorker = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("تصفية الشغل");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("تصفية حساب مجموعة");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("اختر المجموعة");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comWork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("تصفية الحساب");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("اجمالي الوزن");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtwight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtwight.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("اجمالي المبلغ");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("اجمالي المصروفات");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtExpention.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExpention.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("عدد العمال");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCount.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabPanel.setToolTipText("");

        Ghorbal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt1.setText("تلت اللودر");
        txt1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtLoder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLoder.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt4.setText("التلتين");
        txt4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtTthirds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTthirds.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt2.setText("الغربال");
        txt2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtGhorbal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGhorbal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt5.setText("العربية");
        txt5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtworks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtworks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt3.setText("العمال");
        txt3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtoneWork.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtoneWork.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt6.setText("العامل الواحد");
        txt6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout GhorbalLayout = new javax.swing.GroupLayout(Ghorbal);
        Ghorbal.setLayout(GhorbalLayout);
        GhorbalLayout.setHorizontalGroup(
            GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GhorbalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTthirds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtoneWork, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLoder, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(txtGhorbal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtworks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addContainerGap())
        );
        GhorbalLayout.setVerticalGroup(
            GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GhorbalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtLoder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTthirds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGhorbal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txt5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtworks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtoneWork, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tabPanel.addTab("غربال", Ghorbal);

        Ston.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("الصافي");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtHfilter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHfilter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("النصف");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtHtow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHtow.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txxtHassets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txxtHassets.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("مصروفات تشغيل");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        machin.setSelected(true);
        machin.setText("مكنة و هلتي");
        machin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        machin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        machin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machinActionPerformed(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("الي حساب");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comAccount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("حق العامل");
        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtHworker.setEditable(false);
        txtHworker.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHworker.setEnabled(false);
        txtHworker.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHworkerKeyTyped(evt);
            }
        });

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("صافي الحساب");
        jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtClear.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        edWorker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gold/account/pencil.png"))); // NOI18N
        edWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edWorkerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StonLayout = new javax.swing.GroupLayout(Ston);
        Ston.setLayout(StonLayout);
        StonLayout.setHorizontalGroup(
            StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StonLayout.createSequentialGroup()
                        .addComponent(comAccount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtHtow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StonLayout.createSequentialGroup()
                        .addComponent(edWorker, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHworker, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(machin, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StonLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtHfilter, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StonLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txxtHassets, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        StonLayout.setVerticalGroup(
            StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StonLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHtow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHfilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txxtHassets, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(machin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comAccount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHworker, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabPanel.addTab("حجر", Ston);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setText("طباعة");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ترحيل التصفية");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comWork, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtExpention, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtwight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(tabPanel)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comWork, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtwight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExpention, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    txtHworker.getDocument().addDocumentListener(new DocumentListener() {
//            @Override
//            public void insertUpdate(DocumentEvent e) {
//                double edWorker = Double.valueOf(txtHworker.getText());
//                double difr =  HworKer - edWorker;
//                double allDif = difr * Integer.parseInt(txtCount.getText());
//                String txt = txtClear.getText(); 
//                double toClear = Double.valueOf(txt)+ allDif;
//                txtClear.setText(String.valueOf(toClear));
//            }
//
//            @Override
//            public void removeUpdate(DocumentEvent e) {
//                double edWorker = Double.valueOf(txtHworker.getText());
//                double difr =  HworKer - edWorker;
//                double allDif = difr * Integer.parseInt(txtCount.getText());
//                String txt = txtClear.getText(); 
//                double toClear = Double.valueOf(txt)+ allDif;
//                txtClear.setText(String.valueOf(toClear));
//            }
//
//            @Override
//            public void changedUpdate(DocumentEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//            }
//        });
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
 
        ConectionDataBase.fillCombo("workgroup", "name_workgroup", comWork);
        comWork.addItem("اختر اسم المجموعة");
        comWork.setSelectedItem("اختر اسم المجموعة");
        
        tabPanel.setEnabled(false);
        tabPanel.setTitleAt(0, null);
        tabPanel.setTitleAt(1, null);
        
        txt1.setText(null);//تلت اللودر
        txt2.setText(null);//الغربال
        txt3.setText(null);//العمال
        txt4.setText(null);//التلتين
        txt5.setText(null);//العربية
        txt6.setText(null);//العامل الواحد
        
        txtwight.setText("0.00");
        txtExpention.setText("0.00");
        txtAmount.setText("0.00");
        txtCount.setText("0");
    }//GEN-LAST:event_formWindowOpened
    private double  total , Expens , amount , expens;
    private int workerCount;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConectionDataBase.fillCombo("account", "name_account", comAccount);
        comAccount.setSelectedItem("عماد");
        String nameWorkGroup = comWork.getSelectedItem().toString();
        if(nameWorkGroup.equals("اختر اسم المجموعة")){
             Tools.ErorBox("الرجاء اختيار اسم المجموعة");
           
        }else{
            id_work = ConectionDataBase.getIdFrmName("workgroup", nameWorkGroup);
            String SqlSumWight = "SELECT SUM(wight_imports) AS sum FROM imports WHERE id_workgroup = "+id_work+" AND  isRelay = 0;";
            String sumWight = ConectionDataBase.getSum(SqlSumWight);
            txtwight.setText(sumWight);
            String SqlSumAmount = "SELECT SUM(amount_imports) AS sum FROM imports WHERE id_workgroup = "+id_work+" AND  isRelay = 0;";
            String sumAmount = ConectionDataBase.getSum(SqlSumAmount);
            txtAmount.setText(sumAmount);
            String sqlSumExiption = "SELECT SUM(price_expens) AS sum FROM expens WHERE id_workgroup = "+id_work+" AND  isRelay = 0;";
            String SumExepens = ConectionDataBase.getSum(sqlSumExiption);
            txtExpention.setText(SumExepens);
             String selectDeal = "SELECT id_deal AS sum FROM workgroup WHERE id_workgroup="+id_work+";";
             id_deal = ConectionDataBase.getSum(selectDeal);
             String id_type = "";
             String counWorker ="";
            switch (id_deal){
                case "1": 
                    id_type = "2";
                    tabPanel.setEnabled(true);
                    tabPanel.setTitleAt(0, "غربال");
                    tabPanel.setTitleAt(1, null);
                    tabPanel.setSelectedIndex(0);
                    tabPanel.setEnabledAt(1, false);
                    tabPanel.setEnabledAt(0, true);
                    //tabPanel.setTitleAt(1, null);

                    txt1.setText("تلت اللودر");//تلت اللودر
                    txt2.setText("الغربال");//الغربال
                    txt3.setText("العمال");//العمال
                    txt4.setText("التلتين");//التلتين
                    txt5.setText("العربية");//العربية
                    txt6.setText("العامل الواحد");//العامل الواحد
                                
                    String sqlCountWorker = "SELECT COUNT(id_account) AS sum FROM account WHERE id_workgroup = "+id_work+" AND id_type = "+id_type+";";
                    counWorker = ConectionDataBase.getSum(sqlCountWorker);
                    txtCount.setText(counWorker);
                    
                    amount = Double.valueOf(txtAmount.getText());
                    int loder = (int) (amount / 3);
                    txtLoder.setText(String.valueOf(loder));
                    int Towthird = loder*2 ;
                    txtTthirds.setText(String.valueOf(Towthird));
                    expens = Double.valueOf(txtExpention.getText());
                    int clear = (int) (Towthird - expens);
                    int oneThird = clear / 3 ;
                    txtworks.setText(String.valueOf(oneThird));
                     workerCount = Integer.valueOf(txtCount.getText());
                    int OneWorker = oneThird / workerCount;
                    txtoneWork.setText(String.valueOf(OneWorker));
                    int GhorbalAndCar = oneThird - OneWorker;
                    txtGhorbal.setText(String.valueOf(GhorbalAndCar));
                    txtCar.setText(String.valueOf(GhorbalAndCar));
                    
            

                    break;
                case "2":
                    id_type = "8";
                    tabPanel.setEnabled(true);
                    tabPanel.setTitleAt(1, "حجر");
                    tabPanel.setTitleAt(0, null);
                    tabPanel.setSelectedIndex(1);
                    tabPanel.setEnabledAt(0, false);
                    tabPanel.setEnabledAt(1, true);
                    sqlCountWorker = "SELECT COUNT(id_account) AS sum FROM account WHERE id_workgroup = "+id_work+" AND id_type = "+id_type+";";
                    counWorker = ConectionDataBase.getSum(sqlCountWorker);
                    machin.setSelected(true);
                    
                    int countWrker = Integer.parseInt(counWorker)+1;
                    txtCount.setText(""+countWrker);
                    comAccount.setEnabled(true);
                    
                    total = Double.valueOf(txtAmount.getText());
                    Expens = Double.valueOf(txtExpention.getText());
                    int filter = (int)(total - Expens);
                    txtHfilter.setText(filter+".00");
                    int htow = filter/2;
                    txtHtow.setText(htow+".00");
                    String sumAssets = ConectionDataBase.getSum("SELECT SUM(price_assets) AS sum FROM assets WHERE id_workgroup ="+id_work+" AND isRelay = 0;");
                    txxtHassets.setText(sumAssets);
                    double assets =Double.valueOf(sumAssets);
                    double tow = Double.valueOf(htow);
                    f = tow - assets;
                    txtClear.setText(""+f);
                    double hWorker = tow / countWrker;
                    HworKer = hWorker;
                    txtHworker.setText(""+hWorker);
                    
                    break;
                default:
                    Tools.ErorBox("الاتفاق؟؟");
                    break;
            } 
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void machinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machinActionPerformed
        // TODO add your handling code here:
        if(machin.isSelected()){
           comAccount.setEnabled(true);
           String sqlCountWorker = "SELECT COUNT(id_account) AS sum FROM account WHERE id_workgroup = "+id_work+" AND id_type = 8 ;";
           String counWorker = ConectionDataBase.getSum(sqlCountWorker);
           int countWrker = Integer.parseInt(counWorker)+1;
           double tow = Double.valueOf(txtHtow.getText());
           double oneWorker = tow/ countWrker;
           txtHworker.setText(oneWorker+"");
           txtCount.setText(""+countWrker);
           HworKer = oneWorker;
        }
        else{
           comAccount.setEnabled(false);
           String sqlCountWorker = "SELECT COUNT(id_account) AS sum FROM account WHERE id_workgroup = "+id_work+" AND id_type = 8 ;";
           String counWorker = ConectionDataBase.getSum(sqlCountWorker);
           int countWrker = Integer.parseInt(counWorker);
           double tow = Double.valueOf(txtHtow.getText());
           double oneWorker = tow/ countWrker;
           txtHworker.setText(oneWorker+"");
           txtCount.setText(""+countWrker);
           HworKer = oneWorker;
        }
        
    }//GEN-LAST:event_machinActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        

        
      String id_Clear = ConectionDataBase.AutoId("clear", "id_clear");
      SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-dd");
      Date date = new Date();
      String Sdate = format.format(date);
      String note = "تصفية شغل "+comWork.getSelectedItem().toString() + " اجمالي الوزن " + txtwight.getText();
      //Insert Data to Clear Table 
      String Sql = "INSERT INTO clear VALUES("+id_Clear+",'"+Sdate+"','"+note+"');";
      boolean isInsert = ConectionDataBase.ExecuteAnyQuery(Sql);
      String SqlUpdateImport = "UPDATE imports SET isRelay = 1 ,id_clear  = "+id_Clear+" WHERE id_workgroup="+id_work+" AND isRelay=0;";
      String SqlUpdateExpens = "UPDATE expens SET isRelay = 1 ,id_clear  = "+id_Clear+" WHERE id_workgroup="+id_work+" AND isRelay=0;";
      String SqlUpdateAssets = "UPDATE assets SET isRelay = 1 ,id_clear  = "+id_Clear+" WHERE id_workgroup="+id_work+" AND isRelay=0;";
      if(isInsert){
          switch(id_deal){
              case "1":
                  boolean UpImp = ConectionDataBase.ExecuteAnyQuery(SqlUpdateImport);
                  boolean UpExp = ConectionDataBase.ExecuteAnyQuery(SqlUpdateExpens);
                  boolean isUpdate = UpImp && UpExp ;
                  if(isUpdate){
                      //String id_work , String id_type , String amount ,String id_clear ,String note
                     String[] namesWorker = ConectionDataBase.setClearGhorbal(id_work,"2",txtoneWork.getText(),id_Clear,note);
                     // insert into Ghorbal acount
                     String[] Ghorbal = ConectionDataBase.setClearGhorbal(id_work,"5",txtGhorbal.getText(),id_Clear,note);
                     //insert into Car
                     String[] cars = ConectionDataBase.setClearGhorbal(id_work, "1", txtCar.getText(), id_Clear, note);
                     // insert into my Account
                     String id_cred = AutoId("creditors", "id_credit");
                     boolean upLoder = ExecuteAnyQuery("INSERT INTO creditors VALUES("+id_cred +",'"+Sdate+"',"+txtLoder.getText() + ",24,"+id_Clear+",'"+note+"');");
                     if(upLoder){
                       ConectionDataBase.newBalance("24");
                       Tools.MasgBox("تم ترحيل التصفية الي حساب " + "عرفه");
                     }
                     String[] name = (String[]) ArrayUtils.addAll(namesWorker, cars);
                     String[] names = (String[])ArrayUtils.addAll(name, Ghorbal);
                     int count = names.length;
                     for(int i =0 ; i <= count ;i++){
                        Tools.MasgBox("تم ترحيل التصفية الي حساب " + names[i]);
                     }
                  } 
                  break;
               case"2":
                   break;
          }
      }else{
      
      }
      
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtHworkerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHworkerKeyTyped

    }//GEN-LAST:event_txtHworkerKeyTyped

    private void edWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edWorkerActionPerformed
        // TODO add your handling code here:
        if(txtHworker.isEditable()){
            txtHworker.setEditable(false);
        }else{
            txtHworker.setEditable(true);
        }
        if(txtHworker.isEnabled()){
            txtHworker.setEnabled(false);
        }else{
            txtHworker.setEnabled(true);
        }
    }//GEN-LAST:event_edWorkerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       switch(id_deal){
           case "1":
               try{
            InputStream stream = getClass().getResourceAsStream("/Rebort/ClearGhorbalReport.jrxml");
            JasperDesign jd = JRXmlLoader.load(stream); 
            String sql = "SELECT * FROM workgroup WHERE id_workgroup="+id_work+";";
            JRDesignQuery designQuery = new JRDesignQuery();
            designQuery.setText(sql);
            jd.setQuery(designQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            HashMap map = new HashMap();
            map.put("sumImport", amount);
            int id = Integer.parseInt(id_work);
            map.put("id_workgroup", id);
            map.put("SumExpen", expens);
            map.put("CountWorker", workerCount);
            Connection con = ConectionDataBase.getCon();
            JasperPrint jp = JasperFillManager.fillReport(jr, map, con);
            JasperViewer.viewReport(jp,false);
            }catch(Exception ex){
                Tools.ErorBox(ex.getMessage());  
            } 
               break;
           case "2":
               try{
                     InputStream stream = getClass().getResourceAsStream("/Rebort/ClearStonReport.jrxml");
                     JasperDesign jp = JRXmlLoader.load(stream);
                     String sql = "SELECT * FROM workgroup WHERE id_workgroup="+id_work+";";
                     JRDesignQuery query = new JRDesignQuery();
                     query.setText(sql);
                     jp.setQuery(query);
                     JasperReport jr = JasperCompileManager.compileReport(jp);
                     HashMap map = new HashMap();
                     int id = Integer.parseInt(id_work);
                     map.put("id_workgroup", id);
                     map.put("SumImport", total);
                     map.put("SumExpens", Expens);
                     map.put("CountWorker", Integer.parseInt(txtCount.getText()));
                     Connection con = ConectionDataBase.getCon();
                     JasperPrint print = JasperFillManager.fillReport(jr, map, con);
                     JasperViewer.viewReport(print , false);
                     
                    }catch(Exception ex){
                        Tools.ErorBox(ex.getMessage());
                    }
                break;
           default:
               break;
       
       }
        
        
 
        
             
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clearing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clearing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clearing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clearing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clearing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ghorbal;
    private javax.swing.JPanel Ston;
    private javax.swing.JComboBox comAccount;
    private javax.swing.JComboBox comWork;
    private javax.swing.JToggleButton edWorker;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox machin;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JLabel txt6;
    private javax.swing.JLabel txtAmount;
    private javax.swing.JLabel txtCar;
    private javax.swing.JLabel txtClear;
    private javax.swing.JLabel txtCount;
    private javax.swing.JLabel txtExpention;
    private javax.swing.JLabel txtGhorbal;
    private javax.swing.JLabel txtHfilter;
    private javax.swing.JLabel txtHtow;
    private javax.swing.JTextField txtHworker;
    private javax.swing.JLabel txtLoder;
    private javax.swing.JLabel txtTthirds;
    private javax.swing.JLabel txtoneWork;
    private javax.swing.JLabel txtwight;
    private javax.swing.JLabel txtworks;
    private javax.swing.JLabel txxtHassets;
    // End of variables declaration//GEN-END:variables
}
