/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gold.account;

import DataBase.ConectionDataBase;
import static DataBase.ConectionDataBase.AutoId;
import static DataBase.ConectionDataBase.ExecuteAnyQuery;
import DataBase.Tools;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.apache.commons.lang.ArrayUtils;

/**
 *
 * @author Masrawy
 */
public class Clearing extends javax.swing.JFrame {

    /**
     * Creates new form Clearing
     */
    
    double HworKer , f;
    private String id_work = "";
    String id_deal ="";
    public Clearing() {
        initComponents();

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comWork = new javax.swing.JComboBox();
        clearing = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtwight = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtExpention = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCount = new javax.swing.JLabel();
        tabPanel = new javax.swing.JTabbedPane();
        Ghorbal = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        txtLoder = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        txtTthirds = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        txtGhorbal = new javax.swing.JLabel();
        txt5 = new javax.swing.JLabel();
        txtCar = new javax.swing.JLabel();
        txtworks = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        txtoneWork = new javax.swing.JLabel();
        txt6 = new javax.swing.JLabel();
        Ston = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtHfilter = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHtow = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txxtHassets = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        machin = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        comAccount = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        txtHworker = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtClear = new javax.swing.JLabel();
        edWorker = new javax.swing.JToggleButton();
        Bocklen = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtBoclen = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtArea = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtBworker = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtworkerOne = new javax.swing.JTextField();
        checkworker = new javax.swing.JCheckBox();
        comAcount = new javax.swing.JComboBox<>();
        checkworker1 = new javax.swing.JCheckBox();
        comAcount1 = new javax.swing.JComboBox<>();
        history = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("تصفية الشغل");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/budget_1.png"))); // NOI18N
        jLabel1.setText("تصفية حساب مجموعة");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("اختر المجموعة");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comWork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        clearing.setBackground(new java.awt.Color(255, 204, 204));
        clearing.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clearing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calculator.png"))); // NOI18N
        clearing.setText("تصفية الحساب");
        clearing.setOpaque(false);
        clearing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearingActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("اجمالي الوزن");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtwight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtwight.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("اجمالي المبلغ");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("اجمالي المصروفات");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtExpention.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExpention.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("عدد العمال");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCount.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabPanel.setToolTipText("");

        Ghorbal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt1.setText("تلت اللودر");
        txt1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtLoder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLoder.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt4.setText("التلتين");
        txt4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtTthirds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTthirds.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt2.setText("الغربال");
        txt2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtGhorbal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGhorbal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt5.setText("العربية");
        txt5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtworks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtworks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt3.setText("العمال");
        txt3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtoneWork.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtoneWork.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt6.setText("العامل الواحد");
        txt6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout GhorbalLayout = new javax.swing.GroupLayout(Ghorbal);
        Ghorbal.setLayout(GhorbalLayout);
        GhorbalLayout.setHorizontalGroup(
            GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GhorbalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTthirds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtoneWork, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLoder, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(txtGhorbal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtworks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addContainerGap())
        );
        GhorbalLayout.setVerticalGroup(
            GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GhorbalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtLoder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTthirds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGhorbal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txt5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GhorbalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtworks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtoneWork, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPanel.addTab("غربال", new javax.swing.ImageIcon(getClass().getResource("/icons/loader.png")), Ghorbal); // NOI18N

        Ston.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("الصافي");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtHfilter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHfilter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("النصف");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtHtow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHtow.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txxtHassets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txxtHassets.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("مصروفات تشغيل");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        machin.setText("مكنة و هلتي");
        machin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        machin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        machin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machinActionPerformed(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("الي حساب");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comAccount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comAccount.setEnabled(false);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("حق العامل");
        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtHworker.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHworker.setEnabled(false);
        txtHworker.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHworkerKeyTyped(evt);
            }
        });

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("صافي الحساب");
        jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtClear.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        edWorker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gold/account/pencil.png"))); // NOI18N
        edWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edWorkerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StonLayout = new javax.swing.GroupLayout(Ston);
        Ston.setLayout(StonLayout);
        StonLayout.setHorizontalGroup(
            StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StonLayout.createSequentialGroup()
                        .addComponent(comAccount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtHtow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StonLayout.createSequentialGroup()
                        .addComponent(edWorker, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHworker, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(machin, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StonLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtHfilter, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StonLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txxtHassets, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        StonLayout.setVerticalGroup(
            StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StonLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHtow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHfilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txxtHassets, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(machin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comAccount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHworker, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabPanel.addTab("حجر", new javax.swing.ImageIcon(getClass().getResource("/icons/jackhammer.png")), Ston); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("نصيب الحفار");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtBoclen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBoclen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ربع مكان");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("حق العمال");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtBworker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBworker.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("العامل الواحد");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtworkerOne.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        checkworker.setText("حق مكان");
        checkworker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkworker.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        comAcount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        checkworker1.setText("حق عامل");
        checkworker1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkworker1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        comAcount1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout BocklenLayout = new javax.swing.GroupLayout(Bocklen);
        Bocklen.setLayout(BocklenLayout);
        BocklenLayout.setHorizontalGroup(
            BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BocklenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBworker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtworkerOne)
                    .addComponent(comAcount1, 0, 274, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(checkworker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBoclen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comAcount, 0, 222, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(checkworker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BocklenLayout.setVerticalGroup(
            BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(BocklenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BocklenLayout.createSequentialGroup()
                        .addGroup(BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBoclen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BocklenLayout.createSequentialGroup()
                        .addGroup(BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBworker, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtworkerOne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BocklenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BocklenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkworker, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comAcount1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkworker1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BocklenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comAcount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        tabPanel.addTab("حفار", new javax.swing.ImageIcon(getClass().getResource("/icons/digger.png")), Bocklen); // NOI18N

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "البيان", "التاريخ", "الرقم"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout historyLayout = new javax.swing.GroupLayout(history);
        history.setLayout(historyLayout);
        historyLayout.setHorizontalGroup(
            historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
        );
        historyLayout.setVerticalGroup(
            historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        tabPanel.addTab("تصفيات", new javax.swing.ImageIcon(getClass().getResource("/icons/history.png")), history); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printer.png"))); // NOI18N
        btnPrint.setText("طباعة");
        btnPrint.setEnabled(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/navigation.png"))); // NOI18N
        btnClear.setText("ترحيل التصفية");
        btnClear.setEnabled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/history.png"))); // NOI18N
        jButton2.setText("تصفيات سابقة");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(clearing, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comWork, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtExpention, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtwight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(tabPanel)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comWork, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtwight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExpention, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(clearing, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setNew();
    }//GEN-LAST:event_formWindowOpened
    private double  total , Expens , amount , expens;
    private int workerCount;
    private void setNew(){
        ConectionDataBase.NewfillCombo("workgroup", "name_workgroup", comWork);
        comWork.addItem("اختر اسم المجموعة");
        comWork.setSelectedItem("اختر اسم المجموعة");
        tabPanel.setEnabled(false);
        Ghorbal.setEnabled(false);
        Ston.setEnabled(false);
        Bocklen.setEnabled(false);
        history.setEnabled(false);
        tabPanel.setTitleAt(0, null);
        tabPanel.setTitleAt(1, null);
        tabPanel.setTitleAt(2, null);
        tabPanel.setTitleAt(3, null);
        Bocklen.setVisible(false);
        Ston.setVisible(false);
        history.setVisible(false);
        Ghorbal.setVisible(true);
        txt1.setText(null);//تلت اللودر
        txt2.setText(null);//الغربال
        txt3.setText(null);//العمال
        txt4.setText(null);//التلتين
        txt5.setText(null);//العربية
        txt6.setText(null);//العامل الواحد
        txtLoder.setText(null);
        txtTthirds.setText(null);
        txtGhorbal.setText(null);
        txtCar.setText(null);
        txtworks.setText(null);
        txtoneWork.setText(null);
        txtwight.setText("0.00");
        txtExpention.setText("0.00");
        txtAmount.setText("0.00");
        txtCount.setText("0");
        btnClear.setEnabled(false);
        btnPrint.setEnabled(false);
    }
    
    
    private void clearingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearingActionPerformed
        // TODO add your handling code here:
        ConectionDataBase.NewfillCombo("account WHERE isEnable = 0 ", "name_account", comAccount);
        comAccount.setSelectedItem("عماد");
        String nameWorkGroup = comWork.getSelectedItem().toString();
        if(nameWorkGroup.equals("اختر اسم المجموعة")){
             Tools.ErorBox("الرجاء اختيار اسم المجموعة");
           
        }else{
            id_work = ConectionDataBase.getIdFrmName("workgroup", nameWorkGroup);
            String SqlSumWight = "SELECT SUM(wight_imports) AS sum FROM imports WHERE id_workgroup = "+id_work+" AND  isRelay = 0;";
            String sumWight = ConectionDataBase.getSum(SqlSumWight);
            txtwight.setText(sumWight);
            String SqlSumAmount = "SELECT SUM(amount_imports) AS sum FROM imports WHERE id_workgroup = "+id_work+" AND  isRelay = 0;";
            String sumAmount = ConectionDataBase.getSum(SqlSumAmount);
            txtAmount.setText(sumAmount);
            String sqlSumExiption = "SELECT SUM(price_expens) AS sum FROM expens WHERE id_workgroup = "+id_work+" AND  isRelay = 0;";
            String SumExepens = ConectionDataBase.getSum(sqlSumExiption);
            txtExpention.setText(SumExepens);
             String selectDeal = "SELECT id_deal AS sum FROM workgroup WHERE id_workgroup="+id_work+";";
             id_deal = ConectionDataBase.getSum(selectDeal);
             String id_type = "";
             String counWorker ="";
            switch (id_deal){
                case "1": 
                    id_type = "2";
                    tabPanel.setEnabled(true);
                    tabPanel.setTitleAt(0, "غربال");
                    tabPanel.setTitleAt(1, null);
                    tabPanel.setTitleAt(2, null);
                    tabPanel.setTitleAt(3, null);
                    tabPanel.setSelectedIndex(0);
                    tabPanel.setEnabledAt(3, false);
                    tabPanel.setEnabledAt(2, false);
                    tabPanel.setEnabledAt(1, false);
                    tabPanel.setEnabledAt(0, true);
                    //tabPanel.setTitleAt(1, null);
                    Ghorbal.setEnabled(true);
                    txt1.setText("تلت اللودر");//تلت اللودر
                    txt2.setText("الغربال");//الغربال
                    txt3.setText("العمال");//العمال
                    txt4.setText("التلتين");//التلتين
                    txt5.setText("العربية");//العربية
                    txt6.setText("العامل الواحد");//العامل الواحد           
                    //String sqlCountWorker = "SELECT COUNT(id_account) AS sum FROM account WHERE id_workgroup = "+id_work+" AND id_type = "+id_type+" AND isEnable=0;";
                    String sqlCountWorker = "SELECT COUNT(ac.id_account) as sum FROM account ac JOIN accountworkgroup aw ON aw.id_account = ac.id_account WHERE aw.id_workgroup ="+id_work +" AND ac.id_type ="+id_type+" AND ac.isEnable = 0;";
                    counWorker = ConectionDataBase.getSum(sqlCountWorker);
                    txtCount.setText(counWorker);
                    amount = Double.valueOf(txtAmount.getText());
                    int loder = (int) (amount / 3);
                    txtLoder.setText(String.valueOf(loder));
                    int Towthird = loder*2 ;
                    txtTthirds.setText(String.valueOf(Towthird));
                    expens = Double.valueOf(txtExpention.getText());
                    int clear = (int) (Towthird - expens);
                    int oneThird = clear / 3 ;
                    txtworks.setText(String.valueOf(oneThird));
                     workerCount = Integer.valueOf(txtCount.getText());
                    int OneWorker = oneThird / workerCount;
                    txtoneWork.setText(String.valueOf(OneWorker));
                    int GhorbalAndCar = oneThird - OneWorker ;
                    txtGhorbal.setText(String.valueOf(GhorbalAndCar));
                    txtCar.setText(String.valueOf(GhorbalAndCar));
                    break;
                case "2":
                    id_type = "8";
                    tabPanel.setEnabled(true);
                    tabPanel.setTitleAt(1, "حجر");
                    tabPanel.setTitleAt(0, null);
                    tabPanel.setTitleAt(2, null);
                    tabPanel.setTitleAt(3, null);
                    tabPanel.setSelectedIndex(1);
                    tabPanel.setEnabledAt(0, false);
                    tabPanel.setEnabledAt(2, false);
                    tabPanel.setEnabledAt(3, false);
                    tabPanel.setEnabledAt(1, true);
                    Ston.setEnabled(true);
                   // sqlCountWorker = "SELECT COUNT(id_account) AS sum FROM account WHERE id_workgroup = "+id_work+" AND id_type = "+id_type+" AND isEnable=0;;";
                    sqlCountWorker = "SELECT COUNT(ac.id_account) as sum FROM account ac JOIN accountworkgroup aw ON aw.id_account = ac.id_account WHERE aw.id_workgroup ="+id_work +" AND ac.id_type ="+id_type+" AND ac.isEnable = 0;";  
                    counWorker = ConectionDataBase.getSum(sqlCountWorker);
//                    machin.setSelected(true);
                    
                    int countWrker = Integer.parseInt(counWorker);
                    txtCount.setText(""+countWrker);
//                    comAccount.setEnabled(true);
                    
                    total = Double.valueOf(txtAmount.getText());
                    Expens = Double.valueOf(txtExpention.getText());
                    int filter = (int)(total - Expens);
                    txtHfilter.setText(filter+".00");
                    int htow = filter/2;
                    txtHtow.setText(htow+".00");
                    String sumAssets = ConectionDataBase.getSum("SELECT SUM(price_assets) AS sum FROM assets WHERE id_workgroup ="+id_work+" AND isRelay = 0;");
                    txxtHassets.setText(sumAssets);
                    double assets =Double.valueOf(sumAssets);
                    double tow = Double.valueOf(htow);
                    f = tow - assets;
                    txtClear.setText(""+f);
                    double hWorker = tow / countWrker;
                    HworKer = hWorker;
                    txtHworker.setText(""+hWorker);
                    
                    break;
                case "4":
                    ConectionDataBase.NewfillCombo("account WHERE isEnable = 0 ", "name_account", comAcount);
                    ConectionDataBase.NewfillCombo("account WHERE isEnable = 0 ", "name_account", comAcount1);
                    id_type = "8";
                    tabPanel.setEnabled(true);
                    tabPanel.setTitleAt(0,null);
                    tabPanel.setTitleAt(1, null);
                    tabPanel.setTitleAt(3, null);
                    tabPanel.setTitleAt(2, "حفار");
                    tabPanel.setSelectedIndex(2);
                    tabPanel.setEnabledAt(3, false);
                    tabPanel.setEnabledAt(2, true);
                    tabPanel.setEnabledAt(1, false);
                    tabPanel.setEnabledAt(0, false);
                    Bocklen.setEnabled(true);
                    sqlCountWorker = "SELECT COUNT(ac.id_account) as sum FROM account ac JOIN accountworkgroup aw ON aw.id_account = ac.id_account WHERE aw.id_workgroup ="+id_work +" AND ac.id_type ="+id_type+" AND ac.isEnable = 0;";  
                    counWorker = ConectionDataBase.getSum(sqlCountWorker);
                    txtCount.setText(counWorker);
                    double Half = Double.parseDouble(txtAmount.getText());
                    Half = Half / 2 ;
                    double HalfClaer = Half - Double.parseDouble(txtExpention.getText());
                    txtBoclen.setText(HalfClaer+"");
                    double HalfArea = Half / 2;
                    txtArea.setText(HalfArea+"");
                    txtBworker.setText(HalfArea+"");
                    double workerOne = HalfArea / Integer.parseInt(txtCount.getText());
                    txtworkerOne.setText(workerOne+"");
                    break;
                default:
                    Tools.ErorBox("الاتفاق؟؟");
                    break;
            } 
           btnClear.setEnabled(true);
           btnPrint.setEnabled(true);
        }
    }//GEN-LAST:event_clearingActionPerformed

    private void machinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machinActionPerformed

      String  sqlCountWorker = "SELECT COUNT(ac.id_account) as sum FROM account ac JOIN accountworkgroup aw ON aw.id_account = ac.id_account WHERE aw.id_workgroup ="+id_work +" AND ac.id_type = 8 AND ac.isEnable = 0;";
      String counWorker = ConectionDataBase.getSum(sqlCountWorker);   
      double Half = Double.parseDouble(txtHtow.getText()); 
      if(machin.isSelected()){
          comAccount.setEnabled(true);
          int cw = Integer.parseInt(counWorker) + 1 ;
          txtCount.setText(cw+"");  
          int count = Integer.parseInt(txtCount.getText());
          double oneOfWorker = Half / count;
          txtHworker.setText(oneOfWorker+"");
        }else{
            comAccount.setEnabled(false);
            txtCount.setText(counWorker); 
            int count = Integer.parseInt(txtCount.getText());
            double oneOfWorker = Half / count;
           txtHworker.setText(oneOfWorker+"");
        }


        

    }//GEN-LAST:event_machinActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
      String Sql , SqlUpdateImport , SqlUpdateExpens , SqlUpdateAssets ;
      boolean isInsert , UpImp ,UpExp ,isUpdate ,UpAst ;
      String id_Clear = ConectionDataBase.AutoId("clear", "id_clear");
      SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-dd");
      Date date = new Date();
      String Sdate = format.format(date);
      String note = "تصفية شغل "+comWork.getSelectedItem().toString() + " اجمالي الوزن " + txtwight.getText();
      int okOrCancel = JOptionPane.showConfirmDialog(null,"هل ترغب في ترحيل التصفية","ترحيل التصفية",JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);
      if(okOrCancel == JOptionPane.OK_OPTION){
      //Insert Data to Clear Table 
          Sql = "INSERT INTO clear VALUES("+id_Clear+",'"+Sdate+"','"+note+"');";
          isInsert = ConectionDataBase.ExecuteAnyQuery(Sql);
          SqlUpdateImport = "UPDATE imports SET isRelay = 1 ,id_clear  = "+id_Clear+" WHERE id_workgroup="+id_work+" AND isRelay=0;";
          SqlUpdateExpens = "UPDATE expens SET isRelay = 1 ,id_clear  = "+id_Clear+" WHERE id_workgroup="+id_work+" AND isRelay=0;";
          SqlUpdateAssets = "UPDATE assets SET isRelay = 1 ,id_clear  = "+id_Clear+" WHERE id_workgroup="+id_work+" AND isRelay=0;";
          if(isInsert){
              switch(id_deal){
                  case "1":
                      UpImp = ConectionDataBase.ExecuteAnyQuery(SqlUpdateImport);
                      UpExp = ConectionDataBase.ExecuteAnyQuery(SqlUpdateExpens);
                      isUpdate = UpImp && UpExp ;
                      if(isUpdate){
                          //String id_work , String id_type , String amount ,String id_clear ,String note
                         String[] namesWorker = ConectionDataBase.setClearGhorbal(id_work,"2",txtoneWork.getText(),id_Clear,note);
                         // insert into Ghorbal acount
                         String[] SGhorbal = ConectionDataBase.setClearGhorbal(id_work,"5",txtGhorbal.getText(),id_Clear,note);
                         //insert into Car
                         String[] cars = ConectionDataBase.setClearGhorbal(id_work, "1", txtCar.getText(), id_Clear, note);
                         // insert into my Account
                         String id_cred = AutoId("creditors", "id_credit");
                         boolean upLoder = ExecuteAnyQuery("INSERT INTO creditors VALUES("+id_cred +",'"+Sdate+"',"+txtLoder.getText() + ",24,"+id_Clear+",'"+note+"',0);");
                         if(upLoder){
                           ConectionDataBase.newBalance("24");
                           Tools.MasgBox("تم ترحيل التصفية الي حساب " + "عرفه");
                         }
                         String[] name = (String[]) ArrayUtils.addAll(namesWorker, cars);
                         String[] names = (String[])ArrayUtils.addAll(name, SGhorbal);
                         int count = names.length;
                         for(int i =0 ; i < count ;i++){
                            Tools.MasgBox("تم ترحيل التصفية الي حساب " + names[i]);
                         //   System.out.println("تم ترحيل التصفية الي حساب " + names[i]);
                         }
                      } 
                      break;
                   case"2":
                      UpImp = ConectionDataBase.ExecuteAnyQuery(SqlUpdateImport);
                      UpExp = ConectionDataBase.ExecuteAnyQuery(SqlUpdateExpens);
                      UpAst = ConectionDataBase.ExecuteAnyQuery(SqlUpdateAssets);
                      isUpdate = UpImp && UpExp && UpAst ;  
                      if(isUpdate){
                       String[] names = ConectionDataBase.setClear(id_work, "8", txtHworker.getText(), note, id_Clear, txtClear.getText(),machin.isSelected() , comAccount.getSelectedItem().toString());
                       int count = names.length;
                       for(int i=0 ; i < count ; i++){
                           Tools.MasgBox("تم ترحيل التصفية الي حساب " + names[i]);
                         //  System.out.println("تم ترحيل التصفية الي حساب " + names[i]);
                        }
                      }
                       break;
              }
              setNew();
          }else{
              Tools.ErorBox("خطأ");
          }
      }

    }//GEN-LAST:event_btnClearActionPerformed

    private void txtHworkerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHworkerKeyTyped

    }//GEN-LAST:event_txtHworkerKeyTyped

    private void edWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edWorkerActionPerformed

        if(txtHworker.isEnabled()){
            txtHworker.setEnabled(false);
           
        }else{
           
            txtHworker.setEnabled(true);
            Lisenr();
        }
         machin.setEnabled(false);
        
        
    }//GEN-LAST:event_edWorkerActionPerformed
    private void Lisenr(){
        txtHworker.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                double edWorker = Double.valueOf(txtHworker.getText());
                double difr =  HworKer - edWorker;
                double allDif = difr * Integer.parseInt(txtCount.getText());
                double toClear =  f + allDif;
                txtClear.setText(String.valueOf(toClear));
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                double edWorker = Double.valueOf(txtHworker.getText());
                double difr =  HworKer - edWorker;
                double allDif = difr * Integer.parseInt(txtCount.getText());
                double toClear =  f + allDif;
                txtClear.setText(String.valueOf(toClear));

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });        
    
    }
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
       if(tabPanel.isEnabledAt(3)){
            String nameWorkGroup = comWork.getSelectedItem().toString();
            String id_workgroup = ConectionDataBase.getIdFrmName("workgroup", comWork.getSelectedItem().toString());
            if(nameWorkGroup.equals("اختر اسم المجموعة")){
                 Tools.ErorBox("الرجاء اختيار اسم المجموعة");  
            }
            else{
                String selectDeal = "SELECT id_deal AS sum FROM workgroup WHERE id_workgroup="+id_workgroup+";";
                String sql = "SELECT * FROM workgroup WHERE id_workgroup="+id_workgroup+";";
                id_deal = ConectionDataBase.getSum(selectDeal);
                String id_type = "" ;
                switch(id_deal){
                   case "1":
                       id_type = "2";
                         try{
                            InputStream stream = getClass().getResourceAsStream("/Rebort/ClearGhorbalReport_1.jrxml");
                            HashMap map = new HashMap();
                            amount = Double.parseDouble(txtAmount.getText());
                            map.put("sumImport", amount);
                            int id = Integer.parseInt(id_workgroup);
                            map.put("id_workgroup", id);
                            expens = Double.parseDouble(txtExpention.getText());
                            map.put("SumExpen", expens);
                            workerCount = Integer.parseInt(txtCount.getText());
                            map.put("CountWorker", workerCount);
                            int id_clear = Integer.parseInt(table.getValueAt(table.getSelectedRow(), 2).toString());
                            map.put("id_clear", id_clear);
                            Tools.Printer(sql, stream, map);
                        }
                        catch(NumberFormatException ex){
                            Tools.ErorBox(ex.getMessage());  
                        }                        
                       break;
                   case "2":
                       id_type = "8";
                       break;
                   case "4":
                       id_type = "8";
                       break;
                   default:
                       break;

                }                
            }
       } 
       else{  
          String sql = "SELECT * FROM workgroup WHERE id_workgroup="+id_work+";";
           switch(id_deal){
               case "1":
                 try{
                    InputStream stream = getClass().getResourceAsStream("/Rebort/ClearGhorbalReport.jrxml");
                    HashMap map = new HashMap();
                    map.put("sumImport", amount);
                    int id = Integer.parseInt(id_work);
                    map.put("id_workgroup", id);
                    map.put("SumExpen", expens);
                    map.put("CountWorker", workerCount);
                    Tools.Printer(sql, stream, map);
                }
                catch(NumberFormatException ex){
                    Tools.ErorBox(ex.getMessage());  
                } 
                break;
               case "2":
                   try{
                     InputStream stream = getClass().getResourceAsStream("/Rebort/ClearStonReport.jrxml");
                     HashMap map = new HashMap();
                     int id = Integer.parseInt(id_work);
                     map.put("id_workgroup", id);
                     map.put("SumImport", total);
                     map.put("SumExpens", Expens);
                     map.put("CountWorker", Integer.parseInt(txtCount.getText()));
                     Tools.Printer(sql, stream, map);
                    }
                   catch(NumberFormatException ex){
                            Tools.ErorBox(ex.getMessage());
                        }
                    break;
               default:
                   break;
           }
       }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tabPanel.setEnabled(true);
        tabPanel.setTitleAt(1, null);
        tabPanel.setTitleAt(0, null);
        tabPanel.setTitleAt(2, null);
        tabPanel.setTitleAt(3, "السجل");
        tabPanel.setSelectedIndex(3);
        tabPanel.setEnabledAt(0, false);
        tabPanel.setEnabledAt(2, false);
        tabPanel.setEnabledAt(3, true);
        tabPanel.setEnabledAt(1, false);
        history.setEnabled(true);
        btnPrint.setEnabled(true);
        String sql = "SELECT notes ,date_clear , id_clear   FROM clear";
        String [] coulmnName = new String[]{ "البيان", "التاريخ", "الرقم"};
        ConectionDataBase.fillAndCenterTable(sql, table, coulmnName);
        clearing.setEnabled(false);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        String id_clear = table.getValueAt(row, 2).toString();
        String id_workGroup = ConectionDataBase.getSum("SELECT id_workgroup AS sum FROM expens WHERE id_clear ="+id_clear+" GROUP BY id_workgroup;");
        String nameWorkGroup = ConectionDataBase.getSum("SELECT name_workgroup AS sum FROM workgroup WHERE id_workgroup = "+id_workGroup + ";");
        comWork.setSelectedItem(nameWorkGroup);
        //SELECT SUM(wight_imports) as sum FROM imports WHERE id_clear = 1;
        String wight = ConectionDataBase.getSum("SELECT SUM(wight_imports) as sum FROM imports WHERE id_clear = "+id_clear+";");
        txtwight.setText(wight);
        //SELECT SUM(price_expens) as sum FROM expens WHERE id_clear = 1
        String price_expens = ConectionDataBase.getSum("SELECT SUM(price_expens) as sum FROM expens WHERE id_clear = "+id_clear+";");
        txtExpention.setText(price_expens);
        //SELECT SUM(amount_imports) as sum FROM imports WHERE id_clear = 1;
        String amounts = ConectionDataBase.getSum("SELECT SUM(amount_imports) as sum FROM imports WHERE id_clear = "+id_clear+";");
        txtAmount.setText(amounts);
        //SELECT COUNT(aw.id_account) FROM accountworkgroup aw INNER JOIN account a on a.id_account = aw.id_account where a.id_type = 2 and aw.id_workgroup = 1
        String selectDeal = "SELECT id_deal AS sum FROM workgroup WHERE id_workgroup="+id_workGroup+";";
        id_deal = ConectionDataBase.getSum(selectDeal);
        String id_type = "" ;
        switch(id_deal){
           case "1":
               id_type = "2";
               break;
           case "2":
               id_type = "8";
               break;
           case "4":
               id_type = "8";
               break;
           default:
               break;
        
        }
        
        //SELECT COUNT(creditors.id_account) FROM creditors INNER JOIN account on creditors.id_account = account.id_account WHERE account.id_type = 8 and creditors.id_clear = 1
        //SELECT creditors.id_account , account.name_account FROM creditors INNER JOIN account on creditors.id_account = account.id_account WHERE account.id_type = 8 and creditors.id_clear = 1

        
        String SqlcountWorker = "SELECT COUNT(creditors.id_account) AS sum FROM creditors"
                           + " INNER JOIN account on creditors.id_account = account.id_account "
                           + " WHERE account.id_type = "+id_type+" and creditors.id_clear = "+id_clear+";";
        
        String CountWorker = ConectionDataBase.getSum(SqlcountWorker);
        txtCount.setText(CountWorker);
        
        
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clearing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clearing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clearing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clearing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clearing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bocklen;
    private javax.swing.JPanel Ghorbal;
    private javax.swing.JPanel Ston;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrint;
    private javax.swing.JCheckBox checkworker;
    private javax.swing.JCheckBox checkworker1;
    private javax.swing.JButton clearing;
    private javax.swing.JComboBox comAccount;
    private javax.swing.JComboBox<String> comAcount;
    private javax.swing.JComboBox<String> comAcount1;
    private javax.swing.JComboBox comWork;
    private javax.swing.JToggleButton edWorker;
    private javax.swing.JPanel history;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox machin;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTable table;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JLabel txt6;
    private javax.swing.JLabel txtAmount;
    private javax.swing.JLabel txtArea;
    private javax.swing.JLabel txtBoclen;
    private javax.swing.JLabel txtBworker;
    private javax.swing.JLabel txtCar;
    private javax.swing.JLabel txtClear;
    private javax.swing.JLabel txtCount;
    private javax.swing.JLabel txtExpention;
    private javax.swing.JLabel txtGhorbal;
    private javax.swing.JLabel txtHfilter;
    private javax.swing.JLabel txtHtow;
    private javax.swing.JTextField txtHworker;
    private javax.swing.JLabel txtLoder;
    private javax.swing.JLabel txtTthirds;
    private javax.swing.JLabel txtoneWork;
    private javax.swing.JLabel txtwight;
    private javax.swing.JTextField txtworkerOne;
    private javax.swing.JLabel txtworks;
    private javax.swing.JLabel txxtHassets;
    // End of variables declaration//GEN-END:variables
}
