/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gold.account;

import DataBase.ConectionDataBase;
import DataBase.Tools;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mostafa Youssef 
 */
public class Export extends javax.swing.JFrame {

    public Export() {
        initComponents();
    }
     
    private void SetNew(){
        Tools.SearchField(table_export, txtSearch);
        // table 
        String sql = "SELECT suppliers.name_Suppliers,exports.note , exports.price_export , account.name_account , exports.date_exports , exports.id_exports , exports.id_daily FROM exports"
                    + " INNER JOIN account ON exports.id_account = account.id_account "
                    +" INNER JOIN suppliers ON exports.id_Suppliers = suppliers.id_Suppliers  "
                    + " ORDER BY id_exports DESC  ; ";
        String[] coulmnName = new String [] {"مورد","البيان", "المبلغ", "الحساب", "التاريخ", "رقم", "قيد اليومية"};
        ConectionDataBase.fillAndCenterTable(sql, table_export, coulmnName);
        //txt
        txtDate.setEnabled(true);
        String id_daily = ConectionDataBase.AutoId("daily", "id_daily");
        txtDaily.setText(id_daily);
        txtDate.setDate(new Date());
        String id = ConectionDataBase.AutoId("exports", "id_exports");
        txtId.setText(id);
        txtNote.setEnabled(true);
        txtPrice.setEnabled(true);
        txtPrice.setRequestFocusEnabled(true);
        txtPrice.setText("0.00");
        txtNote.setText("");
        comAccount.setEnabled(true);
        comSupplier.setEnabled(true);
        ConectionDataBase.NewfillCombo("account WHERE isEnable = 0 ","name_account", comAccount);
        ConectionDataBase.NewfillCombo("suppliers", "name_Suppliers", comSupplier);
        //btns
        btnNew.setEnabled(false);
        btnDel.setEnabled(false);
        btnEdit.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnSave.setEnabled(true);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comAccount = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        txtDaily = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comSupplier = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_export = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("صادر للحسابات");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("رقم الصادر");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtId.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("التاريخ");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("المبلغ");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("الحساب");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("البيان");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtNote.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtDaily.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDaily.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("المورد");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comSupplier.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comSupplierItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDaily, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comSupplier, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNote)
                    .addComponent(txtDaily, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        table_export.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "مورد", "البيان", "المبلغ", "الحساب", "التاريخ", "رقم", "قيد اليومية"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_export.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_exportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_export);
        if (table_export.getColumnModel().getColumnCount() > 0) {
            table_export.getColumnModel().getColumn(2).setMinWidth(150);
            table_export.getColumnModel().getColumn(2).setPreferredWidth(150);
            table_export.getColumnModel().getColumn(2).setMaxWidth(150);
            table_export.getColumnModel().getColumn(4).setMinWidth(150);
            table_export.getColumnModel().getColumn(4).setPreferredWidth(150);
            table_export.getColumnModel().getColumn(4).setMaxWidth(150);
            table_export.getColumnModel().getColumn(5).setMinWidth(50);
            table_export.getColumnModel().getColumn(5).setPreferredWidth(50);
            table_export.getColumnModel().getColumn(5).setMaxWidth(50);
            table_export.getColumnModel().getColumn(6).setMinWidth(60);
            table_export.getColumnModel().getColumn(6).setPreferredWidth(60);
            table_export.getColumnModel().getColumn(6).setMaxWidth(60);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        btnNew.setText("جديد");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/diskette (1).png"))); // NOI18N
        btnSave.setText("حفظ");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil (1).png"))); // NOI18N
        btnEdit.setText("تعديل");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exchange.png"))); // NOI18N
        btnUpdate.setText("تحديث");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btnDel.setText("حذف");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        btnExit.setText("خروج");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );

        txtSearch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        SetNew();
    }//GEN-LAST:event_formWindowOpened

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String id = txtId.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
        String date = sdf.format(txtDate.getDate());
        String price = txtPrice.getText();
        String id_account = ConectionDataBase.getIdFrmName("account", comAccount.getSelectedItem().toString());
        String id_supllier = ConectionDataBase.getIdFrmName("suppliers", comSupplier.getSelectedItem().toString());
        double price_ex = Double.valueOf(price);
        if(price_ex==0.00){
            Tools.ErorBox("المبلغ غير مكتوب");
        }
        else{
            String sql = "INSERT INTO exports VALUES("+id +",'"+date+"' , "+price+", "+ id_account+" , '"+txtNote.getText()+"',"+id_supllier+",0,"+txtDaily.getText()+" ) ;";
            boolean isSaved = ConectionDataBase.ExecuteAnyQuery(sql);
            if(isSaved){
                
                String tabName = "حساب"+" "+comAccount.getSelectedItem().toString();
                ConectionDataBase.newBalance(id_account);
                int id_sup = Integer.parseInt(id_supllier);
                if(id_sup == 1){
                    String sqlDaily = "INSERT INTO daily VALUES("+txtDaily.getText()+","+id +",'"+date+"' , "+price+",'"+txtNote.getText()+"','"+tabName+"');";
                    ConectionDataBase.ExecuteAnyQuery(sqlDaily);
                }
                else{
                    String id_imSupplier = txtDaily.getText();
                    String sqlImSupplier = "INSERT INTO imsuppliers VALUES("+id_imSupplier+","+id_supllier+","+id+",'"+date+"',"+price+",'"+txtNote.getText()+"','"+tabName+"' , 0);"; 
                    ConectionDataBase.ExecuteAnyQuery(sqlImSupplier);
                    String now_balance = "الرصيد الحالي للمورد  : "+ConectionDataBase.SetNBalanceSuppliers(id_supllier);
                    Tools.MasgBox(now_balance);
                }
                ConectionDataBase.newBalance(id_account);
                String newBalance = ConectionDataBase.getSum("SELECT now_balance AS sum FROM account WHERE id_account="+id_account+";");
                Tools.MasgBox("تم الحفظ بنجاح" + "  والرصيد الحالي " + newBalance);
                SetNew();
                btnNew.setEnabled(false);
            }
            else{
                Tools.ErorBox("خطأ");
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void table_exportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_exportMouseClicked
 
        // txt Disable
        txtDate.setEnabled(false);
        txtId.setEnabled(false);
        txtNote.setEnabled(false);
        txtPrice.setEnabled(false);
        comAccount.setEnabled(false);
        comSupplier.setEnabled(false);
        // Butn Enablse And Disables
        btnDel.setEnabled(true);
        btnEdit.setEnabled(true);
        btnNew.setEnabled(true);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(false);
        
        
        int row = table_export.getSelectedRow();
        comSupplier.setSelectedItem(table_export.getValueAt(row, 0));
        txtNote.setText(table_export.getValueAt(row, 1).toString());
        txtPrice.setText(table_export.getValueAt(row, 2).toString());
        comAccount.setSelectedItem(table_export.getValueAt(row, 3));
        SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd");
        String date = table_export.getValueAt(row, 4).toString();
        try {
            Date DT= SDF.parse(date);
            
            txtDate.setDate(DT);
        } catch (ParseException ex) {
            Logger.getLogger(Export.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtId.setText(table_export.getValueAt(row, 5).toString());
        txtDaily.setText(table_export.getValueAt(row, 6).toString());
    }//GEN-LAST:event_table_exportMouseClicked

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        SetNew();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:  
        txtDate.setEnabled(true);
        txtNote.setEnabled(true);
        txtPrice.setEnabled(true);
        comAccount.setEnabled(true);
        comSupplier.setEnabled(true);
        // Buttuns Enable and Disable
        btnDel.setEnabled(false);
        btnEdit.setEnabled(false);
        btnNew.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //Difiend All String
        String id  , id_account , price  , nots;
        id = txtId.getText();
        id_account = ConectionDataBase.getIdFrmName("account", comAccount.getSelectedItem().toString());
        price = txtPrice.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
        String date = sdf.format(txtDate.getDate());
        nots = txtNote.getText();
         String id_Suppliers = ConectionDataBase.getIdFrmName("suppliers", comSupplier.getSelectedItem().toString());
        // Set the Sql Statement
        String sql = "UPDATE  exports SET date_exports='"+date+"' , price_export="+price+", id_account="+id_account+", id_Suppliers = "+id_Suppliers+",note='"+nots+"' WHERE id_exports="+id+";";
        String oldIdDaily = ConectionDataBase.getSum("SELECT id_daily AS sum FROM exports WHERE id_exports ="+id+";");
        //String id_Suppliers = ConectionDataBase.getIdFrmName("suppliers", comSupplier.getSelectedItem().toString());
        int supplier = Integer.parseInt(id_Suppliers);
        String idOldSupplier = ConectionDataBase.getSum("SELECT id_Suppliers AS sum FROM exports WHERE id_exports ="+id+";");
        int oldSupplier = Integer.parseInt(idOldSupplier);
        boolean isUpdate = ConectionDataBase.ExecuteAnyQuery(sql);
        if(isUpdate){
          Tools.MasgBox("تم تحديث البيانات");
          String tableName = "حساب"+" "+comAccount.getSelectedItem().toString();
         if(supplier == oldSupplier){ 
             
             String sqlupdate = "";
              if(supplier == 1){
                 sqlupdate ="UPDATE daily SET date_day='"+date+"', price = "+price+",note = '"+nots+"'"+", "+" id = "+id+" ,name_table = '"+tableName+"' WHERE id_daily="+txtDaily.getText()+";";
                 
              }else{
                sqlupdate ="UPDATE imsuppliers SET date_day='"+date+"', price = "+price+",note = '"+nots+"'"+", "+" id_exp = "+id+" ,name_table = '"+tableName+"' WHERE id_ImSuppliers="+txtDaily.getText()+";";
              }
              ConectionDataBase.ExecuteAnyQuery(sqlupdate);
            }
         else{
             if(oldSupplier == 1){
                 //DELETE FROM dailay Table
                 ConectionDataBase.ExecuteAnyQuery("DELETE FROM daily WHERE id_daily="+oldIdDaily+";");
                 // insert into imsuppliers
                 ConectionDataBase.ExecuteAnyQuery("INSERT INTO imsuppliers VALUES("+txtDaily.getText()+","+id_Suppliers+","+id+",'"+date+"',"+price+",'"+nots+"','"+tableName+"' , 0);");
                 
             }
             else if(supplier == 1){
                 //DELETE ImSupp
                 ConectionDataBase.ExecuteAnyQuery("DELETE FROM imSuppliers WHERE id_ImSuppliers ="+oldIdDaily+";" );
                 //Insert into daily
                  String sqlDaily = "INSERT INTO daily VALUES("+txtDaily.getText()+","+id+",'"+date+"',"+price+",'"+nots+"','"+tableName+"');";
                  ConectionDataBase.ExecuteAnyQuery(sqlDaily);
            }
            String now_balance = "الرصيد الحالي للمورد : "+ConectionDataBase.SetNBalanceSuppliers(id_Suppliers);
            Tools.MasgBox(now_balance);
         }
          SetNew();
        }else{
            Tools.ErorBox("خطأ");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText();
        String id_day = txtDaily.getText();
        String id_Suppler = ConectionDataBase.getIdFrmName("suppliers", comSupplier.getSelectedItem().toString());
        int suppliers = Integer.parseInt(id_Suppler);
        if(suppliers == 1){
            ConectionDataBase.ExecuteAnyQuery("DELETE FROM daily WHERE id_daily = " + id_day +";");
        }
        else{
            ConectionDataBase.ExecuteAnyQuery("DELETE FROM imsuppliers WHERE id_imSuppliers = "+ id_day +";" );
             String now_balance = ""+ConectionDataBase.SetNBalanceSuppliers(id_Suppler);
             Tools.MasgBox("رصيد المورد : "+now_balance);
        } 
        String sql = "DELETE FROM exports WHERE id_exports ="+id+";";
        boolean isDel = ConectionDataBase.ExecuteAnyQuery(sql);
        if(isDel){
            String id_acount = ConectionDataBase.getIdFrmName("account", comAccount.getSelectedItem().toString());
            ConectionDataBase.newBalance(id_acount);
            String newBalance = ConectionDataBase.getSum("SELECT now_balance AS sum FROM account WHERE id_account="+id_acount+";");
            Tools.MasgBox("تم الحذف بنجاح" + "  والرصيد الحالي " + newBalance);
            SetNew();
        }else{
            Tools.ErorBox("خطأ");
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void comSupplierItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comSupplierItemStateChanged
        // TODO add your handling code here:
           if(comSupplier.getSelectedItem().toString().equals("نقدي")){
                txtDaily.setText(ConectionDataBase.AutoId("daily", "id_daily"));
            }else{
                txtDaily.setText(ConectionDataBase.AutoId("imsuppliers", "id_Imsuppliers"));
            }

    }//GEN-LAST:event_comSupplierItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Export.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Export.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Export.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Export.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Export().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comAccount;
    private javax.swing.JComboBox<String> comSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_export;
    private javax.swing.JLabel txtDaily;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
