/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gold.account;

import DataBase.ConectionDataBase;
import DataBase.Tools;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author mosta
 */
public class exSuppliers extends javax.swing.JFrame {
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    /** Creates new form exSuppliers */
    public exSuppliers() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comSuppliers = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdaily = new javax.swing.JLabel();
        chClaer = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JLabel();
        chzero = new javax.swing.JCheckBox();
        txtDiscond = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnnew = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("مسلسل");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtId.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("التاريخ");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtdate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtdate.setDateFormatString("dd\\MM\\yyyy");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("المبلغ");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtPrice.setEditable(false);
        txtPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("المورد");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comSuppliers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comSuppliersActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("البيان");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtNote.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("قيد اليومية");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtdaily.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtdaily.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chClaer.setText("تصفية حساب");
        chClaer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        chClaer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chClaer.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chClaer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chClaerActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("الرصيد الحالي");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBalance.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chzero.setText("تصفير الرصيد");
        chzero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        chzero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chzero.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chzero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chzeroActionPerformed(evt);
            }
        });

        txtDiscond.setEditable(false);
        txtDiscond.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNote)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDiscond, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chzero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chClaer)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdaily, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comSuppliers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdaily, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiscond, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chClaer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chzero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "البيان", "المورد", "المبلغ", "التاريخ", "مسلسل", "قيد اليومية"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(150);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(1).setPreferredWidth(140);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(60);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(3).setPreferredWidth(75);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(4).setPreferredWidth(50);
            table.getColumnModel().getColumn(5).setResizable(false);
            table.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        btnnew.setText("جديد");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btnsave.setText("حفظ");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil (1).png"))); // NOI18N
        btnedit.setText("تعديل");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exchange.png"))); // NOI18N
        btnupdate.setText("تحديث");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btndel.setText("حذف");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        btnexit.setText("خروج");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        SetNew();
    }//GEN-LAST:event_formWindowOpened

    private void comSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comSuppliersActionPerformed
        // TODO add your handling code here:
        if(comSuppliers.getSelectedItem().equals("اختر اسم المورد")){
            txtPrice.setEditable(false);
            txtBalance.setText("");
        }else{
       // txtPrice.setEditable(false);
        String id_supplier = ConectionDataBase.getIdFrmName("suppliers", comSuppliers.getSelectedItem().toString());
        //ConectionDataBase.SetNBalanceSuppliers(id_supplier);
        String balance = ConectionDataBase.getSum("SELECT now_balance AS sum FROM suppliers WHERE id_Suppliers ="+id_supplier+";");
        txtBalance.setText(balance);
        txtPrice.setEditable(true);
        }
    }//GEN-LAST:event_comSuppliersActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String name_Supp = comSuppliers.getSelectedItem().toString();
        String id_supp = ConectionDataBase.getIdFrmName("suppliers", name_Supp);
        double price = Double.parseDouble(txtPrice.getText());
        if(price == 0){
              Tools.ErorBox("المبلغ غير مكتوب");
        }
        else{
            Date date = txtdate.getDate();
            String id_daily = txtdaily.getText();
            String note = txtNote.getText();
            String txtDate = format.format(date);
            String sqlClear = "UPDATE exsuppliers SET IsActive = 1 WHERE id_Suppliers = "+id_supp+";";
            String sqlexpClear = "UPDATE imsuppliers SET IsActive = 1 WHERE id_Suppliers = "+id_supp+";";
           // insert into exsuppliers                note += + name_Supp  ;
           String table_name = "الصادر للموردين";
           String sqlDaily = "INSERT INTO daily VALUES("+id_daily+","+txtId.getText()+",'"+txtDate+"',"+price+",' الي حساب "+ name_Supp+"','"+table_name+"');";
           boolean is_saved = ConectionDataBase.ExecuteAnyQuery(sqlDaily);
           String sql = "INSERT INTO exsuppliers VALUES("+txtId.getText()+",'"+txtDate+"',"+id_supp+","+price+",'"+note+"',"+id_daily+",0);";
           if(is_saved){
               ConectionDataBase.ExecuteAnyQuery(sql);
               if(chClaer.isSelected()){
                   ConectionDataBase.SetNBalanceSuppliers(id_supp);
                   String getBalance = ConectionDataBase.getSum("SELECT now_balance AS sum FROM suppliers WHERE id_Suppliers = "+id_supp+";");
                   ConectionDataBase.ExecuteAnyQuery("UPDATE suppliers SET old_Balance = "+getBalance+" WHERE id_Suppliers = "+id_supp+";");
                   ConectionDataBase.ExecuteAnyQuery(sqlClear);
                   ConectionDataBase.ExecuteAnyQuery(sqlexpClear); 
               }
               
               
                ConectionDataBase.SetNBalanceSuppliers(id_supp);
                Tools.MasgBox("تم الدفع و الرصيد الحالي هو " + ConectionDataBase.getSum("SELECT now_balance AS sum FROM suppliers WHERE id_Suppliers = "+id_supp+";"));
                   
               
           }
        }
        SetNew();
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void chClaerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chClaerActionPerformed
        // TODO add your handling code here:
        if(chClaer.isSelected()){
            txtNote.setText("تصفية الحساب");
        }else{
            txtNote.setText("");
        }
    }//GEN-LAST:event_chClaerActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        SetNew();
    }//GEN-LAST:event_btnnewActionPerformed

    private void chzeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chzeroActionPerformed
        // TODO add your handling code here:
        if(chzero.isSelected()){
            txtDiscond.setEditable(true);
            //txtDiscond.setText(txtBalance.getText());
        }else{
            txtDiscond.setEditable(false);
        }
    }//GEN-LAST:event_chzeroActionPerformed

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        // TODO add your handling code here:
        if(chzero.isSelected()){
          if( txtPrice.getText() == null){

              }
                else{
                    txtPrice.getDocument().addDocumentListener(new DocumentListener() {
                        @Override
                        public void insertUpdate(DocumentEvent e) {
                         try{
                            double balance = Double.parseDouble(txtBalance.getText());
                            double payPrice = Double.parseDouble(txtPrice.getText());
                            double disc = balance - payPrice ;
                            txtDiscond.setText(""+disc);
                              }catch(EnumConstantNotPresentException ex){
                                  Tools.ErorBox(ex.getMessage());
                              }
                          //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }

                        @Override
                        public void removeUpdate(DocumentEvent e) {
                         try{
                            double balance = Double.parseDouble(txtBalance.getText());
                            double payPrice = Double.parseDouble(txtPrice.getText());
                            double disc = balance - payPrice ;
                            txtDiscond.setText(""+disc);
                              }catch(EnumConstantNotPresentException ex){
                                  Tools.ErorBox(ex.getMessage());
                              }
                          //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }

                        @Override
                        public void changedUpdate(DocumentEvent e) {
                         try{
                            double balance = Double.parseDouble(txtBalance.getText());
                            double payPrice = Double.parseDouble(txtPrice.getText());
                            double disc = balance - payPrice ;
                            txtDiscond.setText(""+disc);
                              }catch(EnumConstantNotPresentException ex){
                                  Tools.ErorBox(ex.getMessage());
                              }


                           // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }
                    });
                }
        }

    }//GEN-LAST:event_txtPriceKeyReleased

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText();
        int ok = JOptionPane.showConfirmDialog(this, "هل ترغب في الحذف ؟", "حذف", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(ok == JOptionPane.YES_OPTION){
            boolean isDel = ConectionDataBase.ExecuteAnyQuery("DELETE FROM exsuppliers WHERE id_exSuppliers = "+id+";");
            if(isDel){
                String id_sup = ConectionDataBase.getIdFrmName("suppliers", comSuppliers.getSelectedItem().toString());
                ConectionDataBase.SetNBalanceSuppliers(id_sup);
                String balance = ConectionDataBase.getSum("SELECT now_balance AS sum FROM suppliers WHERE id_Suppliers ="+id_sup+";");
                Tools.MasgBox("تم الحذف بنجاح و الرصيد الحالي ل "+comSuppliers.getSelectedItem().toString() +" : " + balance);
                SetNew();
            }
            else{
                Tools.ErorBox("خطأ");
            }
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        txtNote.setText(table.getValueAt(row, 0).toString());
        comSuppliers.setSelectedItem(table.getValueAt(row, 1));
        txtPrice.setText(table.getValueAt(row, 2).toString());
        SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd");
        String date = table.getValueAt(row, 3).toString();
        try {
            Date DT = SDF.parse(date);
            txtdate.setDate(DT);
        } catch (ParseException ex) {
            Logger.getLogger(Export.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtId.setText(table.getValueAt(row, 4).toString());
        txtdaily.setText(table.getValueAt(row, 5).toString());
        
        //txt Disable
        txtdate.setEnabled(false);
        comSuppliers.setEnabled(false);
        txtPrice.setEnabled(false);
        txtNote.setEnabled(false);
        chClaer.setEnabled(false);
        chzero.setEnabled(false);
        
        //Btn Disable
        btnnew.setEnabled(true);
        btnsave.setEnabled(false);
        btnedit.setEnabled(true);
        btndel.setEnabled(true);
        btnupdate.setEnabled(false);
        
        
    }//GEN-LAST:event_tableMouseClicked

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        txtNote.setEnabled(true);
        txtdate.setEnabled(true);
        txtPrice.setEnabled(true);
        comSuppliers.setEnabled(true);
        
        
        btnupdate.setEnabled(true);
        btnedit.setEnabled(false);
        btnnew.setEnabled(true);
        btnsave.setEnabled(false);
        btndel.setEnabled(true);
        
    }//GEN-LAST:event_btneditActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText();
        Date date = txtdate.getDate();
        String txtDate = format.format(date);
        String id_sup = ConectionDataBase.getIdFrmName("suppliers", comSuppliers.getSelectedItem().toString());
        String sqlUpdate = "UPDATE exsuppliers SET date_exSuppliers = '"+txtDate+"' , id_Suppliers = "+id_sup+", price_exSuppliers = "+ txtPrice.getText() 
                           + " , note ='"+txtNote.getText()+"' , id_daily = "+txtdaily.getText()+" WHERE id_exSuppliers = "+id +";";
        boolean isUpdate = ConectionDataBase.ExecuteAnyQuery(sqlUpdate);
        if(isUpdate){
                //String id_sup = ConectionDataBase.getIdFrmName("suppliers", comSuppliers.getSelectedItem().toString());
                ConectionDataBase.SetNBalanceSuppliers(id_sup);
                String balance = ConectionDataBase.getSum("SELECT now_balance AS sum FROM suppliers WHERE id_Suppliers ="+id_sup+";");
                Tools.MasgBox("تم تحديث البيانات  بنجاح و الرصيد الحالي ل "+comSuppliers.getSelectedItem().toString() +" : " + balance);
                SetNew();
            }
            else{
                Tools.ErorBox("خطأ");
            }
    }//GEN-LAST:event_btnupdateActionPerformed
    private void SetNew(){
        ConectionDataBase.NewfillCombo("suppliers WHERE id_Suppliers != 1 ", "name_Suppliers", comSuppliers);
//        if(chzero.isSelected()){
//           txtDiscond.setVisible(true);
//        }else{
//          txtDiscond.setVisible(false);
//        }
//        //
        txtId.setText(ConectionDataBase.AutoId("exsuppliers", "id_exSuppliers"));
        txtdate.setDate(new Date());
        txtPrice.setText("0.00");
        txtNote.setText("");
        txtdaily.setText(ConectionDataBase.AutoId("daily", "id_daily"));
        chClaer.setSelected(false);
        chzero.setSelected(false);
        String sql ="SELECT exsuppliers.note , suppliers.name_Suppliers ,exsuppliers.price_exSuppliers ,exsuppliers.date_exSuppliers ,exsuppliers.id_exSuppliers ,exsuppliers.id_daily FROM exsuppliers"
                + " INNER JOIN suppliers ON  exsuppliers.id_Suppliers = suppliers.id_Suppliers;";
        String[] colunm = new  String[]{"البيان", "المورد", "المبلغ", "التاريخ", "مسلسل", "قيد اليومية"};
        ConectionDataBase.fillAndCenterTable(sql, table, colunm);
        comSuppliers.addItem("اختر اسم المورد");
        comSuppliers.setSelectedItem("اختر اسم المورد");
      
        btnnew.setEnabled(false);
        btnsave.setEnabled(true);
        btnedit.setEnabled(false);
        btnupdate.setEnabled(false);
        btndel.setEnabled(false);
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exSuppliers().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JCheckBox chClaer;
    private javax.swing.JCheckBox chzero;
    private javax.swing.JComboBox<String> comSuppliers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JLabel txtBalance;
    private javax.swing.JTextField txtDiscond;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JLabel txtdaily;
    private com.toedter.calendar.JDateChooser txtdate;
    // End of variables declaration//GEN-END:variables

}
