/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gold.account;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.util.Duration;
/**
 *
 * @author mostafa
 */
public class notifiction extends javax.swing.JFrame {
//rgba(112, 111, 211,1.0)
    /**
     * Creates new form notifiction
     */
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    int y = dim.height -160;
    int x = dim.width - 165;
    String msg = "";     
    JFXPanel jfx = new JFXPanel();
    String uri = new File("bip.mp3").toURI().toString();
    MediaPlayer media =  new MediaPlayer(new Media(uri));
    public notifiction(String msg) { 
        media.setStartTime(Duration.ZERO);
        media.play();
        setUndecorated(true); 
        setLocation(x, y-160);
        initComponents();
        jLabel2.setBackground(new Color(112, 111, 211));
        this.msg = msg;
        newNotification();
        
    }
    //rgb(112, 111, 211)
    private void newNotification(){

       new Thread(new Runnable() {
           @Override
           public void run() {
               try {
                   for(int i = 0 ; i <125 ; i++){
                     y = dim.height -i-35; 
                     setLocation(x, y);
                     Thread.sleep(20);
                   }
                   Thread.sleep(1000);
                   for(int i = 0 ; i <= 140 ; i++){
                     y = dim.height - 160;  
                     y = y  + i; 
                     setLocation(x, y);
                     Thread.sleep(20);
                     if(i == 140){
                         media.stop();
                         dispose();
                     }
                   }
           
               } catch (InterruptedException ex) {
                   Logger.getLogger(notifiction.class.getName()).log(Level.SEVERE, null, ex);
               }
           
           }
       }).start();
       
       if(msg.equals("")){
           msg = "إشعار";
       }
       txtmsg.setText(msg);

        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtmsg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(160, 120));
        setResizable(false);

        txtmsg.setBackground(new java.awt.Color(255, 204, 102));
        txtmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtmsg.setText("اشعار");
        txtmsg.setOpaque(true);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/notification.png"))); // NOI18N
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
            .addComponent(txtmsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(notifiction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(notifiction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(notifiction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(notifiction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new notifiction("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtmsg;
    // End of variables declaration//GEN-END:variables
}
